name: Rust CI

on:
  push:
    branches: [ "rust-implementation" ]
  pull_request:
    branches: [ "rust-implementation" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --release --verbose
      working-directory: client_rust
    
    - name: Run tests
      run: cargo test --release --verbose
      working-directory: client_rust
      if: runner.os != 'Windows'

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: client_rust-${{ matrix.os }}
        path: |
          client_rust/target/release/client_rust
          client_rust/target/release/client_rust.exe
